source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.1"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

gem "figaro"

gem "rack-cors", :require => "rack/cors"

gem 'devise'

gem 'devise-jwt'

gem 'jsonapi-serializer'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do


end

